# Generated by Django 5.2.1 on 2025-06-24 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_remove_vote_message_vote_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='pointingsession',
            name='moderator',
        ),
        migrations.AlterModelOptions(
            name='pointingsession',
            options={'verbose_name': 'Voting Session', 'verbose_name_plural': 'Voting Sessions'},
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
