# Generated by Django 5.2.1 on 2025-06-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_pointingsession_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointingsession',
            name='is_open',
            field=models.BooleanField(default=1, help_text='Voting is currently open, default=False'),
            preserve_default=False,
        ),
    ]
