# Generated by Django 5.2.1 on 2025-06-24 05:26

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_pointingsession_is_open'),
    ]


    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(help_text='A project title within the organization.', max_length=120)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),

        migrations.AlterField(
            model_name='pointingsession',
            name='session_date',
            field=models.DateTimeField(verbose_name='Voting window'),
        ),
    ]





