# Generated by Django 5.2.1 on 2025-06-24 05:26

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0007_project_alter_pointingsession_session_date_and_more'),
    ]

    def initial_project(apps, schema_editor):
        # Make sure we have a starter project to FK our sessions to
        Project = apps.get_model("points", "Project")
        if not Project.objects.exists():
            Project.objects.create(name="Default Project")


    operations = [

        migrations.RunPython(initial_project),
        migrations.AddField(
            model_name='pointingsession',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='points.project'),
            preserve_default=False,
        ),
    ]





