# Generated by Django 5.2.1 on 2025-06-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0008_project_alter_pointingsession_session_date_and_more-copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointingsession',
            name='is_open',
            field=models.BooleanField(default=False, help_text='Voting is currently open'),
        ),
    ]
