# Generated by Django 5.2.1 on 2025-06-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0009_alter_pointingsession_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='active',
            field=models.BooleanField(default=False, help_text='Only one ticket may be marked active per voting session.', null=True),
        ),
    ]
