# Generated by Django 5.2.1 on 2025-06-24 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0012_rename_pointingsession_space'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={'get_latest_by': 'modified'},
        ),
        migrations.RemoveField(
            model_name='space',
            name='session_date',
        ),
    ]
