# Generated by Django 5.2.1 on 2025-06-24 22:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0013_alter_space_options_remove_space_session_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='space',
            unique_together={('project', 'moderator')},
        ),
    ]
