# Generated by Django 5.2.1 on 2025-06-24 23:12

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0014_alter_space_options_alter_space_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['project', 'moderator']),
        ),
    ]
