# Generated by Django 5.2.1 on 2025-06-24 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0015_space_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='pointing_session',
            new_name='space',
        ),
    ]
