# Generated by Django 5.1.4 on 2025-06-25 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0016_rename_pointing_session_ticket_space"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="members",
            field=models.ManyToManyField(
                help_text="Users who have joined this space.",
                related_name="members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
