# Generated by Django 5.1.4 on 2025-06-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0017_space_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="voted",
            field=models.BooleanField(
                default=False,
                help_text="Moderator has marked voting complete for this ticket.",
            ),
        ),
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
