# Generated by Django 5.1.4 on 2025-06-29 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0018_ticket_voted_delete_vote"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["id"]},
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="voted",
            new_name="closed",
        ),
    ]
