# Generated by Django 5.1.4 on 2025-06-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0020_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="Tickets from former sessions don't appear on board at all, but we keep them.",
            ),
        ),
    ]
