# Generated by Django 5.1.4 on 2025-06-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0022_broadcastmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcastmessage",
            name="space_name",
            field=models.CharField(default="general", max_length=100),
        ),
    ]
