# Generated by Django 5.1.4 on 2025-06-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0023_broadcastmessage_space_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="broadcastmessage",
            old_name="space_name",
            new_name="room_name",
        ),
    ]
