# Generated by Django 5.1.4 on 2025-06-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0024_rename_space_name_broadcastmessage_room_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BroadcastMessage",
        ),
    ]
