# Generated by Django 5.1.4 on 2025-07-17 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0025_delete_broadcastmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have joined this space.",
                related_name="members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
