# Generated by Django 4.1.3 on 2022-12-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("someapp", "0002_dummy_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dummy",
            name="attachment",
            field=models.FileField(
                blank=True, max_length=256, null=True, upload_to="attachments"
            ),
        ),
    ]
