# Generated by Django 3.2.5 on 2021-07-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy',
            name='attachment',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to='attachments/'),
        ),
    ]
